package com.baomidou.mybatisx.plugin.resultmap;

import com.intellij.database.model.DasColumn;
import com.intellij.database.model.DasNamespace;
import com.intellij.database.model.DasTable;
import com.intellij.database.model.DasTableKey;
import com.intellij.database.model.MultiRef;
import com.intellij.database.model.ObjectKind;
import com.intellij.database.model.DataType;
import com.intellij.database.psi.DbDataSource;
import com.intellij.database.psi.DbPsiFacade;
import com.intellij.database.util.DasUtil;
import com.intellij.openapi.project.Project;
import com.intellij.util.containers.JBIterable;
import org.jetbrains.annotations.NotNull;

import java.sql.Types;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Reads metadata already loaded by IntelliJ Database Tools. It never opens a
 * connection and therefore remains harmless when no data source is configured.
 */
public final class IntellijSqlMetadataProvider implements SqlMetadataProvider {

  @Override
  public @NotNull List<SqlColumnModel> findColumns(@NotNull Project project, @NotNull Set<String> tableNames) {
    List<SqlColumnModel> result = new ArrayList<>();
    Set<String> requested = new HashSet<>();
    for (String table : tableNames) {
      requested.add(normalize(table));
    }
    DbPsiFacade facade = DbPsiFacade.getInstance(project);
    for (DbDataSource dataSource : facade.getDataSources()) {
      for (DasNamespace schema : DasUtil.getSchemas(dataSource)) {
        for (String tableName : tableNames) {
          DasTable table = DasUtil.findChild(schema, DasTable.class, ObjectKind.TABLE, tableName);
          if (table == null || !requested.contains(normalize(table.getName()))) {
            continue;
          }
          appendTableColumns(table, result);
        }
      }
    }
    return result;
  }

  private static void appendTableColumns(DasTable table, List<SqlColumnModel> result) {
    Set<String> primaryKeys = new HashSet<>();
    DasTableKey key = DasUtil.getPrimaryKey(table);
    if (key != null) {
      MultiRef.It<? extends com.intellij.database.model.DasTypedObject> refs = key.getColumnsRef().iterate();
      while (refs.hasNext()) {
        String columnName = refs.next();
        primaryKeys.add(normalize(columnName));
      }
    }
    JBIterable<? extends DasColumn> columns = DasUtil.getColumns(table);
    for (DasColumn column : columns) {
      DataType type = column.getDasType().toDataType();
      SqlColumnModel item = new SqlColumnModel(column.getName());
      item.setInferredJavaType(javaType(type));
      item.setJdbcType(jdbcType(type));
      item.setId(primaryKeys.contains(normalize(column.getName())));
      item.setAutoIncrement(DasUtil.isAutoGenerated(column));
      result.add(item);
    }
  }

  private static String normalize(String value) {
    return value == null ? "" : value.replace("`", "").replace("\"", "").toLowerCase(Locale.ROOT);
  }

  private static String jdbcType(DataType type) {
    String name = type == null || type.typeName == null ? "" : type.typeName.toUpperCase(Locale.ROOT);
    if (name.contains("BIGINT")) return "BIGINT";
    if (name.contains("INT")) return "INTEGER";
    if (name.contains("DECIMAL") || name.contains("NUMBER") || name.contains("NUMERIC")) return "DECIMAL";
    if (name.contains("DATE") && !name.contains("TIME")) return "DATE";
    if (name.contains("TIME")) return "TIMESTAMP";
    if (name.contains("BOOL")) return "BOOLEAN";
    if (name.contains("BLOB") || name.contains("BINARY")) return "VARBINARY";
    return "VARCHAR";
  }

  private static String javaType(DataType type) {
    return switch (jdbcType(type)) {
      case "BIGINT" -> "java.lang.Long";
      case "INTEGER" -> "java.lang.Integer";
      case "DECIMAL" -> "java.math.BigDecimal";
      case "DATE" -> "java.time.LocalDate";
      case "TIMESTAMP" -> "java.time.LocalDateTime";
      case "BOOLEAN" -> "java.lang.Boolean";
      case "VARBINARY" -> "byte[]";
      default -> "java.lang.String";
    };
  }
}
