package com.baomidou.mybatisx.util;

import com.baomidou.mybatisx.feat.mybatis.generator.ColumnInfo;
import com.baomidou.mybatisx.feat.mybatis.generator.ConnectionConfig;
import com.baomidou.mybatisx.feat.mybatis.generator.TableInfo;
import com.baomidou.mybatisx.feat.mybatis.generator.plugin.IntellijColumnInfo;
import com.baomidou.mybatisx.feat.mybatis.generator.plugin.IntellijTableInfo;
import org.jetbrains.annotations.NotNull;

import java.sql.Types;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * The type Db tools utils.
 */
public class DbToolsUtils {

  /**
   * Build intellij table info intellij table info.
   *
   * @param currentTable the current table
   * @return the intellij table info
   */
  public static IntellijTableInfo buildIntellijTableInfo(TableInfo currentTable) {
    IntellijTableInfo tableInfo = new IntellijTableInfo();
    tableInfo.setTableName(currentTable.getTableName());
    tableInfo.setDatabaseType(extractDatabaseTypeFromUrl(currentTable));
    tableInfo.setTableRemark(currentTable.getComment());
    tableInfo.setTableType(currentTable.getTableType());
    List<IntellijColumnInfo> intellijColumnInfos = new ArrayList<>();
    for (ColumnInfo column : currentTable.getColumns()) {
      IntellijColumnInfo columnInfo = convertColumnToIntellijColumnInfo(column, tableInfo.getDatabaseType());
      intellijColumnInfos.add(columnInfo);
    }

    tableInfo.setColumnInfos(intellijColumnInfos);
    List<IntellijColumnInfo> primaryColumnInfos = new ArrayList<>();

    Iterator<String> iterate = currentTable.getPrimaryKeyColumnNames();
    if (iterate != null) {
      short s = 0;
      while (iterate.hasNext()) {
        String columnName = iterate.next();
        for (IntellijColumnInfo intellijColumnInfo : intellijColumnInfos) {
          if (columnName.equals(intellijColumnInfo.getName())) {
            IntellijColumnInfo info = copyIntellijColumnInfo(intellijColumnInfo, s);
            primaryColumnInfos.add(info);
            s++;
            break;
          }
        }
      }
    }
    tableInfo.setPrimaryKeyColumns(primaryColumnInfos);
    return tableInfo;
  }

  @NotNull
  private static IntellijColumnInfo copyIntellijColumnInfo(IntellijColumnInfo intellijColumnInfo, short s) {
    IntellijColumnInfo info = new IntellijColumnInfo();
    info.setName(intellijColumnInfo.getName());
    info.setSize(intellijColumnInfo.getSize());
    info.setAutoIncrement(intellijColumnInfo.isAutoIncrement());
    info.setRemarks(intellijColumnInfo.getRemarks());
    info.setNullable(intellijColumnInfo.getNullable());
    info.setDecimalDigits(intellijColumnInfo.getDecimalDigits());
    info.setDataType(intellijColumnInfo.getDataType());
    info.setSize(intellijColumnInfo.getSize());
    info.setColumnDefaultValue(intellijColumnInfo.getColumnDefaultValue());
    info.setGeneratedColumn(intellijColumnInfo.isGeneratedColumn());
    info.setKeySeq(s);
    return info;
  }


  private static String extractDatabaseTypeFromUrl(TableInfo currentTable) {
    ConnectionConfig connectionConfig = currentTable.getConnectionConfig();
    if (connectionConfig == null) {
      return null;
    }
    return extractDatabaseTypeFromUrl(connectionConfig.getUrl());
  }

  /**
   * Extract database type from url string.
   *
   * @param url the url
   * @return the string
   */
  public static String extractDatabaseTypeFromUrl(String url) {
    if (url == null) {
      return "";
    } else {
      url = url.toLowerCase();
      if (url.contains(":mysql")) {
        return "MySql";
      } else if (url.contains(":oracle")) {
        return "Oracle";
      } else if (url.contains(":postgresql")) {
        return "PostgreSQL";
      } else if (url.contains(":sqlserver")) {
        return "SqlServer";
      } else {
        return url.contains(":sqlite") ? "Sqlite" : "";
      }
    }
  }

  /**
   * Convert column to intellij column info intellij column info.
   *
   * @param column       the column
   * @param databaseType the database type
   * @return the intellij column info
   */
  @NotNull
  public static IntellijColumnInfo convertColumnToIntellijColumnInfo(ColumnInfo column, String databaseType) {
    IntellijColumnInfo columnInfo = new IntellijColumnInfo();
    columnInfo.setName(column.getName());
    columnInfo.setDataType(convertTypeNameToJdbcType(column.getDataTypeName(), column.getDataTypeSize(), databaseType));
    if (column.isAutoGenerated()) {
      columnInfo.setGeneratedColumn(true);
    }

    if (column.isAutoGenerated()) {
      columnInfo.setAutoIncrement(true);
    }

    columnInfo.setSize(column.getLength());
    columnInfo.setDecimalDigits(column.getScale());
    columnInfo.setRemarks(column.getComment());
    columnInfo.setColumnDefaultValue(column.getDefault());
    columnInfo.setNullable(!column.isNotNull());
    columnInfo.setKeySeq(column.getPosition());

    return columnInfo;
  }

  /**
   * Convert type name to jdbc type int.
   *
   * @param jdbcTypeName the jdbc type name
   * @param size         the size
   * @param databaseType the database type
   * @return the int
   */
  public static int convertTypeNameToJdbcType(String jdbcTypeName, int size, String databaseType) {
    if (StringUtils.isEmpty(jdbcTypeName)) {
      return Types.OTHER;
    }
    String fixed = jdbcTypeName.toUpperCase();
    if (fixed.contains("BIGINT")) {
      return Types.BIGINT;
    } else if (fixed.contains("TINYINT")) {
      return Types.TINYINT;
    } else if (fixed.contains("LONGVARBINARY")) {
      return Types.LONGVARBINARY;
    } else if (fixed.contains("VARBINARY")) {
      return Types.VARBINARY;
    } else if (fixed.contains("LONGVARCHAR")) {
      return Types.LONGVARCHAR;
    } else if (fixed.contains("SMALLINT")) {
      return Types.SMALLINT;
    } else if (fixed.contains("DATETIME")) {
      return Types.TIMESTAMP;
    } else if (fixed.equals("DATE") && "Oracle".equals(databaseType)) {
      return Types.TIMESTAMP;
    } else if (fixed.contains("NUMBER")) {
      return Types.DECIMAL;
    } else if (fixed.contains("BOOLEAN")) {
      return Types.BOOLEAN;
    } else if (fixed.contains("BINARY")) {
      return Types.VARBINARY;
    } else if (fixed.contains("BIT")) {
      return Types.BIT;
    } else if (fixed.contains("BOOL")) {
      return Types.BOOLEAN;
    } else if (fixed.contains("DATE")) {
      return Types.DATE;
    } else if (fixed.contains("TIMESTAMP")) {
      return Types.TIMESTAMP;
    } else if (fixed.contains("TIME")) {
      return Types.TIME;
    } else if (!fixed.contains("REAL") && !fixed.contains("NUMBER")) {
      if (fixed.contains("FLOAT")) {
        return Types.FLOAT;
      } else if (fixed.contains("DOUBLE")) {
        return Types.DOUBLE;
      } else if ("CHAR".equals(fixed)) {
        return Types.CHAR;
      } else if (fixed.equals("INT")) {
        return Types.INTEGER;
      } else if (fixed.contains("DECIMAL")) {
        return Types.DECIMAL;
      } else if (fixed.contains("NUMERIC")) {
        return Types.NUMERIC;
      } else if (!fixed.contains("CHAR") && !fixed.contains("TEXT")) {
        if (fixed.contains("BLOB")) {
          return Types.BLOB;
        } else if (fixed.contains("CLOB")) {
          return Types.CLOB;
        } else {
          return fixed.contains("REFERENCE") ? Types.REF : Types.OTHER;
        }
      } else {
        return Types.VARCHAR;
      }
    } else {
      return Types.REAL;
    }
  }
}
