package com.baomidou.mybatisx.feat.mybatis.generator;

public interface ColumnInfo {

  String getName();

  String getDataTypeName();

  int getDataTypeSize();

  String getComment();

  String getDefault();

  boolean isNotNull();

  int getPosition();

  int getLength();

  boolean isAutoGenerated();

  int getScale();
}
