package com.baomidou.mybatisx.feat.mybatis.generator;

import com.intellij.database.model.DasColumn;
import com.intellij.database.model.DasTableKey;
import com.intellij.database.psi.DbTable;
import com.intellij.database.util.DasUtil;
import com.intellij.util.containers.JBIterable;

import java.util.Collections;
import java.util.Iterator;

public class PsiTableInfo implements TableInfo {

  private final DbTable dbTable;
  private final ConnectionConfig connectionConfig;

  public PsiTableInfo(DbTable dbTable) {
    this.dbTable = dbTable;
    this.connectionConfig = new PsiConnectionConfig(dbTable.getDataSource().getConnectionConfig());
  }

  @Override
  public String getTableName() {
    return dbTable.getName();
  }

  @Override
  public ConnectionConfig getConnectionConfig() {
    return connectionConfig;
  }

  @Override
  public String getComment() {
    return dbTable.getComment();
  }

  @Override
  public String getTableType() {
    return dbTable.getTypeName();
  }

  @Override
  public ColumnInfo[] getColumns() {
    JBIterable<? extends DasColumn> columns = DasUtil.getColumns(dbTable);
    return columns.map(PsiColumnInfo::new).toArray(new PsiColumnInfo[0]);
  }

  @Override
  public Iterator<String> getPrimaryKeyColumnNames() {
    DasTableKey primaryKey = DasUtil.getPrimaryKey(dbTable);
    if (primaryKey == null) {
      return Collections.emptyIterator();
    }
    return primaryKey.getColumnsRef().iterate();
  }

  static class PsiColumnInfo implements ColumnInfo {
    private final DasColumn column;

    PsiColumnInfo(DasColumn column) {
      this.column = column;
    }

    @Override
    public String getName() {
      return column.getName();
    }

    @Override
    public String getComment() {
      return column.getComment();
    }

    @Override
    public String getDefault() {
      return column.getDefault();
    }

    @Override
    public boolean isNotNull() {
      return !column.isNotNull();
    }

    @Override
    public int getPosition() {
      return column.getPosition();
    }

    @Override
    public int getLength() {
      return column.getDasType().toDataType().getLength();
    }

    @Override
    public boolean isAutoGenerated() {
      return DasUtil.isAutoGenerated(column);
    }

    @Override
    public int getScale() {
      return column.getDasType().toDataType().getScale();
    }

    @Override
    public String getDataTypeName() {
      return column.getDasType().toDataType().typeName;
    }

    @Override
    public int getDataTypeSize() {
      return column.getDasType().toDataType().size;
    }
  }
}
