spring:
    datasource:
        username: sa
        password: ""
        url: jdbc:h2:mem:test
        driver-class-name: org.h2.Driver
        schema: db/schema.sql
logging:
    level:
        com.baomidou: debug
        dao: debug
mybatis-plus:
    mapper-locations: mapper/*.xml
    type-aliases-package: com.baomidou.mybatis3.alias,com.baomidou.mybatis3.domain
    configuration:
        log-prefix: dao.
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


