spring:
    datasource:
        username: sa
        password: ""
        url: jdbc:h2:mem:test
        driver-class-name: org.h2.Driver
        schema: classpath:db/schema.sql
logging:
    level:
        com.baomidou: debug
mybatis-plus:
    mapper-locations: mapper/*.xml
